### ISSUE TITLE
[建议]建议图标可以改为这个

### ISSUE THREAD

**Issue by mengxin10824** [HowcanoeWang/siyuan-genshin-launcher#1]
自己做了两个原神相关的logo，一个是SiYuan Impact，一个是SiYuan Note，用的是原神官方的汉仪文黑 85W Heavy，技术力低整不了啥花活（）
![SiYuan Impact](https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/47906112/2e6ac838-dd6c-40ef-b997-868101d1e67c)
![SiYuan Note](https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/47906112/4fccb078-4727-4479-9257-efea3128c8d9)
估计插件无法改软件图标，但是可以手动改，Mac的话可以在显示简介改，Windows可以在属性面板改，我已经用上了哈哈哈
<img width="377" alt="image" src="https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/47906112/6a792d5a-460c-48de-9b40-2b33b74d72b4">

**Comment by HowcanoeWang** [comment]
mac还真有可能自动替换，windows还得再研究研究

**Comment by HowcanoeWang** [comment]
mac的图标不应该是icns结尾吗，我这边下下来是png替换不了

**Comment by HowcanoeWang** [comment]
@mengxin10824 改了一下，我把字体调大外加改了一下颜色，但是感觉还是看不太清楚

![image](https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/19968935/ce390305-7902-4436-bd02-f5b0a215e231)

**Comment by mengxin10824** [comment]
icns的图标包含多个尺寸的图片文件，而png只有一个尺寸的（）
你把dock栏调大就清楚了（）

**Comment by HowcanoeWang** [comment]
> icns的图标包含多个尺寸的图片文件，而png只有一个尺寸的（） 你把dock栏调大就清楚了（）

Windows和MacOS替换基本都走通了，下周出差回来安排

**Comment by mengxin10824** [comment]
好好好
