### ISSUE TITLE
夜间主题启动加载时使用黑底白图标

### ISSUE THREAD

**Issue by chenshinshi** [HowcanoeWang/siyuan-genshin-launcher#2]
现在的夜间主题默认也是白底黑图标，有点光敏性癫痫（（。

https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/125173405/331a0616-7f4f-4444-b4ed-819b4da4a6a1

**Comment by HowcanoeWang** [comment]
启动页面那个改起来有点费劲，因为本身就没提供两套颜色切换的

可以后续看看，登陆进去后，加载的纯logo页面， 能不能给换成黑色的
