### ISSUE TITLE
提高锁屏时背景动画画质

### ISSUE THREAD

**Issue by QQQOrange** [HowcanoeWang/siyuan-genshin-launcher#7]
现在的画质看起来非常的模糊，希望能够有1080p或者2k的画质

**Comment by HowcanoeWang** [comment]
>  现在的画质看起来非常的模糊，希望能够有1080p或者2k的画质

为了把安装包大小压缩到60mb，已经是当前画面下最优解了

**Comment by QQQOrange** [comment]
> > 现在的画质看起来非常的模糊，希望能够有1080p或者2k的画质
> 
> 为了把安装包大小压缩到60mb，已经是当前画面下最优解了

好吧 谢谢老哥

**Comment by QQQOrange** [comment]
> > 现在的画质看起来非常的模糊，希望能够有1080p或者2k的画质
> 
> 为了把安装包大小压缩到60mb，已经是当前画面下最优解了

老哥能提供一个高画质的包吗？然后想要更高画质的能自己替换

**Comment by HowcanoeWang** [comment]
> 老哥能提供一个高画质的包吗？然后想要更高画质的能自己替换

https://cowtransfer.com/s/1b4d8fb6ed6d4b 点击链接查看 [ siyuan-genshin-launcher ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 kvousl 查看；

**Comment by QQQOrange** [comment]
> > 老哥能提供一个高画质的包吗？然后想要更高画质的能自己替换
> 
> https://cowtransfer.com/s/1b4d8fb6ed6d4b 点击链接查看 [ siyuan-genshin-launcher ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 kvousl 查看；

谢谢老哥！！！！
