### ISSUE TITLE
Not worked for installed from Microsoft Store

### ISSUE THREAD

**Issue by itachaaa** [HowcanoeWang/siyuan-genshin-launcher#8]
是使用admin启动的，但是目录没有权限，是不是只能下载exe安装包的才能使用呢

cp : 对路径“C:\Program Files\WindowsApps\89C2A984.SiYuan_3.0.5.0_x64__1qfd3tsw4ngc2\app\resources\stage\icon-large.png
”的访问被拒绝。
所在位置 行:1 字符: 3772

**Comment by HowcanoeWang** [comment]
对的，Windows商店里的App安装的文件夹权限在管理员之上，如有需要请使用exe安装包安装
